variable "resource_group_name" {}
variable "location" {}
variable "environment" {}
variable "storage_account_name" {}
variable "account_tier" {}
variable "account_replication_type" {}
variable "storage_container_name" {}
variable "container_access_type" {}
variable "blob_name" {}
variable "blob_type" {}
variable "blob_source_location" {}
variable "blob_access_tier" {}