variable "client_id" {}
variable "client_secret" {}
variable "subscription_id" {}
variable "tenant_id" {}
variable "resource_group_name" {}
variable "location" {}
variable "environment" {}
variable "virtualnetwork_name" {}
variable "vnet_address_space" {}
variable "webnsg_name" {}
variable "web_nsg_ports" {}
variable "web_nsg_port_name" {}
variable "appnsg_name" {}
variable "app_nsg_ports" {}
variable "app_nsg_port_name" {}
variable "dbnsg_name" {}
variable "db_nsg_ports" {}
variable "db_nsg_port_name" {}
variable "web_subnet_address_prefix" {}
variable "web_subnet_name" {}
variable "app_subnet_address_prefix" {}
variable "app_subnet_name" {}
variable "db_subnet_address_prefix" {}
variable "db_subnet_name" {}
variable "db_server_name" {}
variable "db_server_admin_username" {}
variable "db_server_admin_password" {}
variable "storage_mb" {}
variable "sku_name" {}
variable "database_name" {}
variable "db_server_firewall_start_ip_address" {}
variable "db_server_firewall_end_ip_address" {}
variable "database_firewall_rule_name" {}
variable "storage_account_name" {}
variable "account_tier" {}
variable "account_replication_type" {}
variable "storage_container_name" {}
variable "container_access_type" {}
variable "blob_name" {}
variable "blob_type" {}
variable "blob_source_location" {}
variable "blob_access_tier" {}