variable "resource_group_name" {}
variable "location" {}
variable "environment" {}
variable "virtualnetwork_name" {}
variable "vnet_address_space" {}
variable "webnsg_name" {}
variable "web_nsg_ports" {}
variable "web_nsg_port_name" {}
variable "appnsg_name" {}
variable "app_nsg_ports" {}
variable "app_nsg_port_name" {}
variable "dbnsg_name" {}
variable "db_nsg_ports" {}
variable "db_nsg_port_name" {}
variable "web_subnet_address_prefix" {}
variable "web_subnet_name" {}
variable "app_subnet_address_prefix" {}
variable "app_subnet_name" {}
variable "db_subnet_address_prefix" {}
variable "db_subnet_name" {}